#!/usr/bin/python3

import sys

def factors(file):
  with open(file, "r") as f:
    for line in f:
      n = int(line)
      for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
          print(f"{n}={i}*{n//i}")
          break

if __name__ == "__main__":
  factors(sys.argv[1])

